### ISSUE TITLE
Live preview bug

### ISSUE THREAD

**Issue by pgaskin** [remarkableapp/Remarkable-Linux#19]
When you drag a file/link on to the live preview, the live preview navigates to the webpage. It will not return to normal until I change the style, open a new file, or restart Remarkable.

**Comment by remarkableapp** [comment]
Dragging files onto the live preview will be blocked in the future. Dragging a plaintext file onto the editor pane will open the file.

[At the minute you can reload the content by changing the text in the editor pane]

**Comment by pgaskin** [comment]
OK
