### ISSUE TITLE
Feature request - Add spell-checker

### ISSUE THREAD

**Issue by frederickjh** [remarkableapp/Remarkable-Linux#20]
Hi!
Thanks for Remarkable! It is great to have a Markup Editor in Linux. On feature that I very much miss from word processors and even my code text editor is a spell checker. Would be good to have the ability to use dictionaries in different languages. Might also be nice to have it check code it finds for spelling errors too.

Thanks for considering this new feature!

Frederick

**Comment by krikmo** [comment]
> Would be good to have the ability to use dictionaries in different languages.

Agreed.

For spell checking in English (and maybe Spanish and German too) you can install [pygtkspellcheck](https://pypi.python.org/pypi/pygtkspellcheck/).

**Comment by frederickjh** [comment]
Hi krikmo!

I installed it with

```
sudo pip install pygtkspellcheck
```

restarted Remarkable but no spellchecking. I checked the menu but I do not find any new settings to turn this on.
Frederick

**Comment by krikmo** [comment]
I first installed the Debian option in Python 2 and had the same issue as you: nothing happened. The version in Python 3 works. What is your distro?

There are no options or settings (as far as I know), the spell checking works with a right-click menu.

**Comment by frederickjh** [comment]
Ah, OK

I uninstalled what I had before with

```
sudo pip uninstall pygtkspellcheck
```

then I installed for Python 3 with

```
sudo apt-get install python3-gtkspellcheck
```

I found that command on the [Python GTK Spellchecker page](http://koehlma.github.io/projects/pygtkspellcheck.html). Now spell checking works on my Ubuntu 14.04.04 setup.

I am changing this feature request to a documentation request that says that spell checking is available, but the Python GTK Spellchecker package must be installed for Python 3. Might also be good to include commands to install and a link to the [Python GTK Spellchecker page](http://koehlma.github.io/projects/pygtkspellcheck.html).

**Comment by krikmo** [comment]
> Might also be good to include commands to install and a link to the Python GTK Spellchecker page.

That's a good idea. Could be added to the README file or in a page in the site.

**Comment by ghost** [comment]
I am waiting for French ...

**Comment by frederickjh** [comment]
@phicarre that is something you need to ask / help work on in the python3-gtkspellcheck package. That is where Remarkable gets its spell checking languages from.

**Comment by frederickjh** [comment]
@phicarre currently the python3-gtkspellcheckh has English, German and Spanish. Maybe there is a separate package for French for it.

**Comment by SamuelMiller** [comment]
Since the python3-gtkspellcheck package is small, how about installing by default on Linux with the menu option to either enable or disable it?
