### ISSUE TITLE
Images do not show using relative paths

### ISSUE THREAD

**Issue by krikmo** [remarkableapp/Remarkable-Linux#25]
If you try `![image](image.jpg)` it will not appear. It would be very useful if it did work.

This is clearly not a bug, consider it a low-priority feature request. :)

**Comment by efine** [comment]
To add a use case to support this: currently, I'm working on a document containing many screenshots. To work with Remarkable (great Markdown editor, by the way - thanks for this!), after I've checked out my document that was checked in with relative image links, I run a script to convert the relative links to absolute links. Once I'm done, I run a script to convert the absolute links back to relative.

Although this isn't a _terminally dreadful_ hassle, I too often forget to reconvert the files, and have to push another commit (or force push). I'm going to add a git pre-commit hook to warn me about this, but it would be really helpful if Remarkable honored relative as well as absolute image links.

**Comment by krikmo** [comment]
Is that script case-specific or generic?

**Comment by efine** [comment]
It's a pretty naïve sed one-liner at heart, but it works for my purposes and you're welcome to hack it to suit your needs.

``` bash
#!/bin/bash

die() {
    echo $* >&2
    exit 1
}

usage() {
    cat <<'END_USAGE'
    usage: localize.sh|generalize.sh markdown-doc

    localize.sh   - converts all "(images/" paths to "($PWD/images/"
                    to facilitate local editing.
    generalize.sh - converts all "($PWD/images/" paths to "(images/"
                    to work on websites.
END_USAGE
    exit 1
}

(( $# == 1 )) || usage

PROG=$(basename $0 .sh)
MD_FILE="$1"; shift

[[ -f $MD_FILE ]] || die "No file $MD_FILE - giving up."
[[ -d images ]] || die "Expected an images subdirectory - giving up."

CURDIR=$(pwd)

case "$PROG" in
    localize)
        sed -i.orig -e "s,(images/,(${CURDIR}/images/,g" $MD_FILE
        ;;
    generalize)
        sed -i.orig.local -e "s,(${CURDIR}/images/,(images/,g" $MD_FILE
        ;;
    *)
        die "Unknown operation $PROG"
        ;;
esac
```

**Comment by efine** [comment]
I'm changing my mind about this. It's becoming so annoying that I now see it as a bug.

If I open `remarkable` in the directory in which the markdown file resides, it _still_ does not insert images with relative links. Is this really hard to fix?

**Comment by remarkableapp** [comment]
This feature was added in V1.75.

The repository is now [located here](https://github.com/jamiemcg/Remarkable).
